json.address1 @post.address1
json.address2 @post.address2
json.city @post.city
json.state @post.state
json.postal @post.postal
json.description @post.description
json.monthly @post.monthly
json.security @post.security
json.last @post.last
json.timeslots @post.calculateTimeslots
